# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIIeWKN-k7LsMf-oBDsUzIdWNcVU_i8z
"""

import pandas as pd


df = pd.read_csv('/content/netflix_titles.csv')


df.head()

df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

df = df.drop_duplicates()

df['country'] = df['country'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Unknown')

print(df.columns)

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

df['type'] = df['type'].str.lower().str.strip()
df['country'] = df['country'].str.lower().str.strip()
df['rating'] = df['rating'].str.upper().str.strip()

df.to_csv('/content/cleaned_netflix_dataset.csv', index=False)

df.head()